name: Get Spot Pricing History

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

concurrency:
  group: fetch-spot-prices

permissions:
  id-token: write
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    if: github.repository == 'orf/spot-prices'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
          mask-aws-account-id: true
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - run: poetry install
      - run: poetry run python -m spot_prices_fetcher fetch
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'spot_price_data/ state.json'
          default_author: github_actions
          message: 'Update Data'
          push: true

  bundle:
    runs-on: ubuntu-latest
    needs: update
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - run: |
          wget -q https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
      - run: ./duckdb -echo -cmd "SET temp_directory='/tmp/duckdb.tmp'; SET enable_progress_bar = true;" < export.sql
      - run: |
          gzip -1 history.sqlite
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+00:00"
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          tag_name: latest
          name: |
            ${{ steps.current-time.outputs.formattedTime }}
          files: |
            history.parquet 
            history.sqlite.gz
          body: |
            Automated bundling of spot prices into a parquet file 
            Updated on ${{ steps.current-time.outputs.formattedTime }}
            See the readme for more information.
