name: Get Spot Pricing History

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

concurrency:
  group: fetch-spot-prices

permissions:
  id-token: write
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    if: github.repository == 'orf/spot-prices'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
          mask-aws-account-id: true
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - run: poetry install
      - run: poetry run python -m spot_prices_fetcher fetch
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'spot_price_data/ state.json'
          default_author: github_actions
          message: 'Update Data'
          push: true