name: Get Spot Pricing History

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - run: poetry install
      - run: poetry run python -m spot_prices_fetcher fetch
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'spot_price_data/ state.json'
          default_author: github_actor
          message: 'Update Data'
          push: true